### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by anderson361163** [EdersomBarros/ProjetoJSP#1]
Olá, Edersom

No seu github, encontrei apenas o readme, porém não o projeto em si. 
Att,

Anderson

**Comment by anderson361163** [comment]
Acabei de localizar o projeto em uma branch diferente.

**Comment by anderson361163** [comment]
Acabei de localizar o projeto em uma branch diferente. Parabéns pelo projeto!

**Comment by EdersomBarros** [comment]
Obrigado Anderson!!! Gostaria sim de algumas dicas. Qual o seu linkedin?
________________________________
De: Anderson da Silva Machado ***@***.***>
Enviado: segunda-feira, 14 de novembro de 2022 14:05
Para: EdersomBarros/ProjetoJSP ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [EdersomBarros/ProjetoJSP] Projeto (Issue #1)


Acabei de localizar o projeto em uma branch diferente. Parabéns pelo projeto!
